In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train =pd.read_csv('fed.csv')
test =pd.read_csv('abc.csv')

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45718 entries, 0 to 45717
Data columns (total 72 columns):
PERID        45718 non-null int64
IFATHER      45718 non-null int64
NRCH17_2     45718 non-null int64
IRHHSIZ2     45718 non-null int64
IIHHSIZ2     45718 non-null int64
IRKI17_2     45718 non-null int64
IIKI17_2     45718 non-null int64
IRHH65_2     45718 non-null int64
IIHH65_2     45718 non-null int64
PRXRETRY     45718 non-null int64
PRXYDATA     45718 non-null int64
MEDICARE     45718 non-null int64
CAIDCHIP     45718 non-null int64
CHAMPUS      45718 non-null int64
PRVHLTIN     45718 non-null int64
GRPHLTIN     45718 non-null int64
HLTINNOS     45718 non-null int64
HLCNOTYR     45718 non-null int64
HLCNOTMO     45718 non-null int64
HLCLAST      45718 non-null int64
HLLOSRSN     45718 non-null int64
HLNVCOST     45718 non-null int64
HLNVOFFR     45718 non-null int64
HLNVREF      45718 non-null int64
HLNVNEED     45718 non-null int64
HLNVSOR      45718 non-null int64
IRMCDCHP     45718 non-null int64
IIMCDCHP     45718 non-null int64
IRMEDICR     45718 non-null int64
IIMEDICR     45718 non-null int64
IRCHMPUS     45718 non-null int64
IICHMPUS     45718 non-null int64
IRPRVHLT     45718 non-null int64
IIPRVHLT     45718 non-null int64
IROTHHLT     45718 non-null int64
IIOTHHLT     45718 non-null int64
HLCALLFG     45718 non-null int64
HLCALL99     45718 non-null int64
ANYHLTI2     45718 non-null int64
IRINSUR4     45718 non-null int64
IIINSUR4     45718 non-null int64
OTHINS       45718 non-null int64
CELLNOTCL    45718 non-null int64
CELLWRKNG    45718 non-null int64
IRFAMSOC     45718 non-null int64
IIFAMSOC     45718 non-null int64
IRFAMSSI     45718 non-null int64
IIFAMSSI     45718 non-null int64
IRFSTAMP     45718 non-null int64
IIFSTAMP     45718 non-null int64
IRFAMPMT     45718 non-null int64
IIFAMPMT     45718 non-null int64
IRFAMSVC     45718 non-null int64
IIFAMSVC     45718 non-null int64
IRWELMOS     45718 non-null int64
IIWELMOS     45718 non-null int64
IRPINC3      45718 non-null int64
IRFAMIN3     45718 non-null int64
IIPINC3      45718 non-null int64
IIFAMIN3     45718 non-null int64
GOVTPROG     45718 non-null int64
POVERTY3     45718 non-null int64
TOOLONG      45718 non-null int64
TROUBUND     45718 non-null int64
PDEN10       45718 non-null int64
COUTYP2      45718 non-null int64
MAIIN102     45718 non-null int64
AIIND102     45718 non-null int64
ANALWT_C     45718 non-null float64
VESTR        45718 non-null int64
VEREP        45718 non-null int64
Criminal     45718 non-null int64
dtypes: float64(1), int64(71)
memory usage: 25.1 MB

In [4]:
train.describe()

,PERID,IFATHER,NRCH17_2,IRHHSIZ2,IIHHSIZ2,IRKI17_2,IIKI17_2,IRHH65_2,IIHH65_2,PRXRETRY,...,TOOLONG,TROUBUND,PDEN10,COUTYP2,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP,Criminal
count,4.571800e+04,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,...,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000,45718.000000
mean,5.445446e+07,3.355549,0.476486,3.426375,1.001706,2.084124,1.007437,1.162606,1.011024,97.394943,...,2.219410,2.234940,1.646135,1.764666,1.978936,1.978739,4692.661179,40023.739118,1.493854,0.069447
std,2.553911e+07,1.176651,0.888472,1.427420,0.061314,1.102988,0.123162,0.469029,0.146444,12.355156,...,5.295784,5.293651,0.618403,0.771411,0.144510,0.145161,5724.659486,265.140430,0.500230,0.254216
min,1.000222e+07,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,3.233189e+07,4.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,99.000000,...,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,1252.396472,40013.000000,1.000000,0.000000
50%,5.411043e+07,4.000000,0.000000,3.000000,1.000000,2.000000,1.000000,1.000000,1.000000,99.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2719.335160,40025.000000,1.000000,0.000000
75%,7.612731e+07,4.000000,1.000000,4.000000,1.000000,3.000000,1.000000,1.000000,1.000000,99.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,5765.810794,40039.000000,2.000000,0.000000
max,9.999956e+07,4.000000,3.000000,6.000000,3.000000,4.000000,3.000000,3.000000,3.000000,99.000000,...,98.000000,98.000000,3.000000,3.000000,2.000000,2.000000,109100.623000,40050.000000,2.000000,1.000000

In [5]:
train.isnull().sum()

PERID        0
IFATHER      0
NRCH17_2     0
IRHHSIZ2     0
IIHHSIZ2     0
IRKI17_2     0
IIKI17_2     0
IRHH65_2     0
IIHH65_2     0
PRXRETRY     0
PRXYDATA     0
MEDICARE     0
CAIDCHIP     0
CHAMPUS      0
PRVHLTIN     0
GRPHLTIN     0
HLTINNOS     0
HLCNOTYR     0
HLCNOTMO     0
HLCLAST      0
HLLOSRSN     0
HLNVCOST     0
HLNVOFFR     0
HLNVREF      0
HLNVNEED     0
HLNVSOR      0
IRMCDCHP     0
IIMCDCHP     0
IRMEDICR     0
IIMEDICR     0
            ..
CELLNOTCL    0
CELLWRKNG    0
IRFAMSOC     0
IIFAMSOC     0
IRFAMSSI     0
IIFAMSSI     0
IRFSTAMP     0
IIFSTAMP     0
IRFAMPMT     0
IIFAMPMT     0
IRFAMSVC     0
IIFAMSVC     0
IRWELMOS     0
IIWELMOS     0
IRPINC3      0
IRFAMIN3     0
IIPINC3      0
IIFAMIN3     0
GOVTPROG     0
POVERTY3     0
TOOLONG      0
TROUBUND     0
PDEN10       0
COUTYP2      0
MAIIN102     0
AIIND102     0
ANALWT_C     0
VESTR        0
VEREP        0
Criminal     0
Length: 72, dtype: int64

In [6]:
feature_name=[x for x in train.columns if x not in ['PERID','Criminal']]
Criminal = train['Criminal']

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

In [8]:
lr = LogisticRegression()

In [9]:
lr.fit(train[feature_name],Criminal)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [11]:
pred = lr.predict(test[feature_name])

In [12]:
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
sub = pd.DataFrame({'PERID' : test['PERID'], 'Criminal' : pred})
col = ['PERID','Criminal']

In [22]:
sub = sub[col]

In [24]:
sub

          PERID  Criminal
0      66583679         0
1      35494679         0
2      79424679         0
3      11744679         0
4      31554679         0
5      83164679         0
6      58474679         0
7      40695779         1
8      39315779         0
9      58415779         0
10     23535779         0
11     67275779         0
12     93485779         0
13     29546779         0
14     97556779         0
15     37797779         0
16     36607779         0
17     61727779         0
18     20827779         0
19     52437779         0
20     87267779         0
21     33287779         0
22     30398779         0
23     98598779         0
24     41818779         0
25     69638779         0
26     25748779         0
27     75368779         0
28     99968779         0
29     91578779         1
...         ...       ...
11400  43750730         0
11401  35360730         0
11402  51380730         0
11403  50480730         0
11404  71901730         0
11405  96021730         0
11406  71331730         0
11407  66541730         1
11408  29861730         0
11409  95071730         0
11410  61281730         0
11411  57202730         0
11412  45402730         0
11413  45022730         0
11414  99432730         0
11415  26732730         0
11416  85832730         0
11417  45782730         0
11418  26493730         0
11419  54693730         0
11420  97103730         0
11421  99713730         0
11422  74543730         0
11423  57863730         0
11424  97294730         0
11425  31894730         1
11426  98524730         0
11427  80134730         0
11428  65323398         0
11429  90906563         0

[11430 rows x 2 columns]

In [25]:
sub.to_csv('first.csv',index = False)

In [28]:
ls=LinearRegression()

In [29]:
ls.fit(train[feature_name],Criminal)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [31]:
pred1=ls.predict(test[feature_name])

0